# Alegra API Integration Test

In [1]:
import numpy as np 
import pandas as pd

In [2]:
from  alegra_integration import search_item_by_name, search_item_by_reference, modify_item_by_reference

product_name = 'PISTOLA DE SILICONA 4" X 1/2" TRUPER'
infos_product = search_item_by_name(product_name) 
print(infos_product)

     ID Referencia                                Nombre  \
0  5723       1849  PISTOLA DE SILICONA 4" X 1/2" TRUPER

               Categoria   Precio  Stock Disponible
0  HERRAMIENTA ELECTRICA  29412 $                 2

We upload the samples after the scrapping to modify them into `Alegra`

In [4]:
electric_tool_truper = pd.read_csv("../notebooks/data/sample_electric_truper_products.csv", sep=";")

In [5]:
electric_tool_truper.head()

,Nombre,Referencia,Unidad de medida,Categoría,Descripción,Costo inicial,Precio base,Impuesto,Precio total,Precio general,Código cuenta contable,Cuenta contable,Código cuenta de inventario,Cuenta de inventario,Código cuenta de costo de venta,Cuenta de costo de venta,Código de barras,Marca
0,DESTORNILLADOR INALAMBRICO BATERIA 3.6V TRUPER,3544,Unidad,HERRAMIENTA ELECTRICA,"{'codigo': '17033', 'descripcion': 'Marca Trup...","57000,000000","82353,000000",19.0,98000,"82353,000000",413505,Ventas,143505.0,Inventarios,613505.0,Costos del inventario,7506240656104,TRUPER 17033
1,LLANA LISA MANGO DE MADERA 6 REMACHES TRUPER,3926,Unidad,HERRAMIENTA MANUAL,"{'codigo': '15406', 'descripcion': 'Marca Trup...","11400,000000","17647,000000",19.0,21000,"17647,000000",413505,Ventas,143505.0,Inventarios,613505.0,Costos del inventario,7501206633762,TRUPER 15406
2,JUEGO DE 7 LLAVES TORX LARGAS CON ORGANIZADOR ...,1368,Unidad,HERRAMIENTA MANUAL,"{'codigo': '15553', 'descripcion': 'Marca Trup...","9657,000000","14706,000000",19.0,17500,"14706,000000",413505,Ventas,143505.0,Inventarios,613505.0,Costos del inventario,7501206626092,TRUPER 15553
3,"MANDRIL ZANCO 7/16"" PARA SIERRA COPA BIMETALIC...",4010,Unidad,HERRAMIENTA MANUAL,"{'codigo': '18123', 'descripcion': ""Marca Trup...","14470,000000","21849,000000",19.0,26000,"21849,000000",413505,Ventas,143505.0,Inventarios,613505.0,Costos del inventario,7501206676943,TRUPER 18123
4,"PISTOLA DE SILICONA 4"" X 1/2"" TRUPER",1849,Unidad,HERRAMIENTA ELECTRICA,"{'codigo': '17536', 'descripcion': 'Marca Trup...","19760,000000","29412,000000",19.0,35000,"29412,000000",413505,Ventas,143505.0,Inventarios,613505.0,Costos del inventario,7501206645390,TRUPER 17536

For all products (DONE)

In [8]:
# for index, row in electric_tool_truper.iterrows():
#     modify_item_by_reference(row["Referencia"], "description", row["Descripción"])
#     infos_product = search_item_by_reference(row["Referencia"]) 
#     if infos_product is not None:
#         print(f"Product {row['Nombre']} updated successfully.")

In [ ]:
# import ast

# def keep_only_codigo(value):
#     try:
#         if isinstance(value, str):
#             value = ast.literal_eval(value)
#         if isinstance(value, dict) and "descripcion" in value:
#             return value["descripcion"]
#     except Exception as e:
#         print(f"Error processing value: {value} — {e}")
#     return value

# electric_tool_truper["Descripción"] = electric_tool_truper["Descripción"].apply(keep_only_codigo)

In [15]:
electric_tool_truper.head()

,Nombre,Referencia,Unidad de medida,Categoría,Descripción,Costo inicial,Precio base,Impuesto,Precio total,Precio general,Código cuenta contable,Cuenta contable,Código cuenta de inventario,Cuenta de inventario,Código cuenta de costo de venta,Cuenta de costo de venta,Código de barras,Marca
0,DESTORNILLADOR INALAMBRICO BATERIA 3.6V TRUPER,3544,Unidad,HERRAMIENTA ELECTRICA,"Marca Truper, Línea 18153, Modelo 18153, Tipo ...","57000,000000","82353,000000",19.0,98000,"82353,000000",413505,Ventas,143505.0,Inventarios,613505.0,Costos del inventario,7506240656104,TRUPER 17033
1,LLANA LISA MANGO DE MADERA 6 REMACHES TRUPER,3926,Unidad,HERRAMIENTA MANUAL,"Marca Truper, Modelo LLM-6L, Tipo de producto ...","11400,000000","17647,000000",19.0,21000,"17647,000000",413505,Ventas,143505.0,Inventarios,613505.0,Costos del inventario,7501206633762,TRUPER 15406
2,JUEGO DE 7 LLAVES TORX LARGAS CON ORGANIZADOR ...,1368,Unidad,HERRAMIENTA MANUAL,"Marca Truper, Modelo Torx-7l, Tipo de llave Co...","9657,000000","14706,000000",19.0,17500,"14706,000000",413505,Ventas,143505.0,Inventarios,613505.0,Costos del inventario,7501206626092,TRUPER 15553
3,"MANDRIL ZANCO 7/16"" PARA SIERRA COPA BIMETALIC...",4010,Unidad,HERRAMIENTA MANUAL,"Marca Truper, Modelo MAND-7/16, Tipo de mandri...","14470,000000","21849,000000",19.0,26000,"21849,000000",413505,Ventas,143505.0,Inventarios,613505.0,Costos del inventario,7501206676943,TRUPER 18123
4,"PISTOLA DE SILICONA 4"" X 1/2"" TRUPER",1849,Unidad,HERRAMIENTA ELECTRICA,"Marca Truper, Modelo PICA-X, Tipo de producto ...","19760,000000","29412,000000",19.0,35000,"29412,000000",413505,Ventas,143505.0,Inventarios,613505.0,Costos del inventario,7501206645390,TRUPER 17536

In [ ]:
# electric_tool_truper.to_csv("../notebooks/data/sample_electric_truper_products.csv", sep=";")